### TYPE YOUR NAME HERE: Anna G. Castillo

## ISM 5644 - Programming for Analytics

## Exam - Coding Section

### Task:
The code cells in this notebook have been left blank. Your task is to complete these cells and provide the execution results. Once you have completed the test, you should publish your notebook code (the code in the .ipynb file) as a "Secret Gist" on your GitHub repository and obtain the Gist ID.

### Submission Format:
There are two deliverables of this exam: 1) the Gist ID and 2) the completed .ipynb file. Both of these should be submitted on Canvas using the corresponding submission link.

### Important: Do not forget to <u>run</u> the cells before submitting the document.

### Question 1:

Note: This question has 2 steps.

Step 1:

Write a function that takes two inputs:

1) a string consisting of a single letter (e.g., 'e')

2) a long string consisting of some letters (e.g., 'HELLo WORld')

and counts how many times the single letter (1st input) occurs in the long string (2nd input). The function should ignore capitalization – i.e., uppercase 'E' should be counted as 'e', etc. The output of the function should be the frequency count of the letter.

#### Q1. Use the cell below to enter your code for this question.

In [6]:
def countLetter_freq(letter, text): 
    return text.lower().count(letter.lower())

Step 2:

Write a loop that iteratively calls the function you developed in the first step to count how many times each letter in a given list (e.g., ['a', 'e', 'o']) occurs in the long string consisting of some letters (2nd input of Step 1).

Below is a sample output after completing both steps.

longString = 'HELLo WORld'

aList = ['a', 'e', 'o']

Output (after defining the function and running the loop): 

The letter a occurs 0 times in the long string.

The letter e occurs 1 times in the long string.

The letter o occurs 2 times in the long string.

In [16]:
longString = 'HELLo WORld'
aList = ['a', 'e', 'o']

for a in aList:
    count = countLetter_freq(a, longString)
    print("The letter", a, "occurs", count, "times in the long string.")

The letter a occurs 0 times in the long string.
The letter e occurs 1 times in the long string.
The letter o occurs 2 times in the long string.

### Question 2:

Assume that there exists a file named “aFile.txt” in the local disk. Write a program that prompts the user for a positive integer n as an input. The program should write the first n characters of each line in “aFile.txt” to a new file, named “newFile.txt”. The program should write the entire line, if n is greater than that line’s length. Below is a sample input and output for n = 10.

Input - aFile.txt:

First line of the file

Second line of the file

Third

Output - newFile.txt:

First line

Second lin

Third

#### Q2. Use the cell below to enter your code for this question.

In [45]:
file = open(r'C:\Users\annac\Downloads\aFile.txt', 'r')
n = input('Enter a positive integer: ')

for line in file:
    cleaned_line = line.strip()
file.close()

new_file = open(r'C:\Users\annac\Downloads\newFile.txt', 'w')
new_fileLen = cleaned_line(len(n))
new_file.write((new_fileLen)+ "\n")
new_file.close()

Enter a positive integer:  10

TypeError: 'str' object is not callable

### Question 3:

Assume that there exists a file named “numbersWords.txt” in the local disk. Each line of this file consists of some integer numbers (int) and words (str). Write a program that finds the largest number in this file, and prints out this number as well as the number of the line this number was in. Below is a sample input and output:

Input - numbersWords.txt:

random 346 numbers and

233 words are in 306

This file you 15663 need to find

4 the largest number here 592

Output:

The largest number: 15663

Found in line: 3

#### Q3. Use the cell below to enter your code for this question.

In [44]:
file = open(r'C:\Users\annac\Downloads\numbersWords.txt', 'r')
largest = 0
line_count = 0

for line in file:
        line = line.strip()
        if not line:
            continue
        
        parts = [part.strip() for part in line.split(" ")]
        number = parts[0]
        count = len(parts) - 1
        
        if count > largest:
            largest = count
            line_count += 1

print('The largest number: ', largest)
print('Found in line: ', line_count)

The largest number:  6
Found in line:  3

### Question 4:

Download the following file to your local machine: NHL_data.csvDownload NHL_data.csv

The data set contains statistics for some of the National Hockey League teams across the years.

Question: Perform the tasks listed below using the Pandas Library. Notice that these tasks are divided into 3 cells. Please only use the designated cell area in the Jupyter file to write down your corresponding code. After importing the file at the beginning, you can continue working on the same data (i.e., you don't need to re-import the data for each individual cell).

Cell #1:

Import the downloaded data into the Python environment as a Pandas DataFrame.
Drop the column titled "GamesPlayed" from the DataFrame.
Select the first 10 observations and the first 5 columns from the data and display the values. Do NOT assign the selection to anything -- simply display the values on the screen.

#### Q4 Cell 1. Use the cell below to enter your code for the 1st cell of Q4.

In [13]:
import pandas as pd
df = pd.read_csv(r'C:\Users\annac\Downloads\NHL_data.csv')
df

,Year,Team,GamesPlayed,Wins,Losses,Shots,ShotsAgainst,PenaltyInMinutes,SeasonWinner
0,2012,LOS ANGELES,20,16,4,30.6,27.0,11.9,Y
1,2012,NEW JERSEY,24,14,10,28.4,27.0,10.3,N
2,2012,NY RANGERS,20,10,10,29.3,27.8,10.9,N
3,2012,PHOENIX,16,9,7,26.7,37.7,14.0,N
4,2012,WASHINGTON,14,7,7,27.6,32.8,8.7,N
...,...,...,...,...,...,...,...,...,...
171,2001,CAROLINA,6,2,4,19.0,33.5,19.2,N
172,2001,PHILADELPHIA,6,2,4,29.3,30.3,12.3,N
173,2001,SAN JOSE,6,2,4,26.8,30.5,14.7,N
174,2001,VANCOUVER,4,0,4,22.0,29.0,12.5,N
175,2001,OTTAWA,4,0,4,30.8,24.8,12.0,N

In [14]:
df.drop(['GamesPlayed'],axis=1)

,Year,Team,Wins,Losses,Shots,ShotsAgainst,PenaltyInMinutes,SeasonWinner
0,2012,LOS ANGELES,16,4,30.6,27.0,11.9,Y
1,2012,NEW JERSEY,14,10,28.4,27.0,10.3,N
2,2012,NY RANGERS,10,10,29.3,27.8,10.9,N
3,2012,PHOENIX,9,7,26.7,37.7,14.0,N
4,2012,WASHINGTON,7,7,27.6,32.8,8.7,N
...,...,...,...,...,...,...,...,...
171,2001,CAROLINA,2,4,19.0,33.5,19.2,N
172,2001,PHILADELPHIA,2,4,29.3,30.3,12.3,N
173,2001,SAN JOSE,2,4,26.8,30.5,14.7,N
174,2001,VANCOUVER,0,4,22.0,29.0,12.5,N
175,2001,OTTAWA,0,4,30.8,24.8,12.0,N

In [15]:
df.iloc[0:10, 0:5]

   Year          Team  GamesPlayed  Wins  Losses
0  2012   LOS ANGELES           20    16       4
1  2012    NEW JERSEY           24    14      10
2  2012    NY RANGERS           20    10      10
3  2012       PHOENIX           16     9       7
4  2012    WASHINGTON           14     7       7
5  2012     NASHVILLE           10     5       5
6  2012  PHILADELPHIA           11     5       6
7  2012      ST LOUIS            9     4       5
8  2012       FLORIDA            7     3       4
9  2012        BOSTON            7     3       4

Cell #2:

Display all observations that had more than 40 "Shots". Show all the columns for these observations.
Select and display all observations in Year 2011 that had more "Wins" than the average number of "Wins" for that particular year (2011).

#### Q4 Cell 2. Use the cell below to enter your code for the 2nd cell of Q4.

In [25]:
df.loc[df['Shots'] > 40,]

,Year,Team,GamesPlayed,Wins,Losses,Shots,ShotsAgainst,PenaltyInMinutes,SeasonWinner
11,2012,CHICAGO,6,2,4,40.2,26.5,14.8,N
41,2010,WASHINGTON,7,3,4,41.7,27.7,9.9,N
143,2003,DETROIT,4,0,4,42.8,30.0,9.0,N

In [55]:
df.loc[df['Year'] > 2011, 'Wins'].value_counts().head(1)

Wins
3    3
Name: count, dtype: int64

Cell #3:

Notice that the "SeasonWinner" column indicates the season winner for a given year (The value of that column is "Y" if winner of the "Year"). Find out which team won the season the most across the years. Do the necessary operation in Pandas and print out a single output (can be a table or a string) that states the team's name and the number of season wins.

#### Q4 Cell 3. Use the cell below to enter your code for the 3rd cell of Q4.